name: Playwright Tests

on:
  deployment_status:
jobs:
  run-e2es:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success' && github.ref != 'ref/head/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install playwright dependencies
        run: pnpm exec playwright install-deps chromium

      - name: Install browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Run tests
        run: pnpm exec playwright test
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
          
      - name: Upload report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
